"""Synthetic Population Explorer - a live Streamlit demo for Project 2.

What this app does, in one breath: it generates a fake patient population with the
project's own `synthea_mini` generator, profiles it with `synthea_explorer`, and
lets you click through the results - population stats, charts, one patient's
timeline, and the FHIR bundle for that patient.

Nothing here touches real patient data. The whole point of the project is that you
practise on invented patients, so this is safe to put on the public internet.

How it finds the project code: this file lives in
    02_synthetic_patients_synthea/hosting/streamlit_app/app.py
and the real packages live in
    02_synthetic_patients_synthea/build_from_scratch/
so we walk up two folders (to the project root) and add build_from_scratch/ to the
import path. After that, `import synthea_mini` works just like it does in a notebook.
"""

import sys
import pathlib
import tempfile
from datetime import date

# --- Make the project's packages importable -------------------------------------
# parents[0] = streamlit_app, parents[1] = hosting, parents[2] = project root.
# Then build_from_scratch/ holds synthea_mini and synthea_explorer.
PROJECT_CODE = pathlib.Path(__file__).resolve().parents[2] / "build_from_scratch"
sys.path.insert(0, str(PROJECT_CODE))

import pandas as pd
import streamlit as st

# These are the real functions from your project - the same ones the tests and the
# notebooks use. If any of these imports fail in the cloud, it almost always means
# build_from_scratch/ didn't get pushed to GitHub alongside hosting/.
from synthea_mini import generate_population, write_tables, build_patient_bundle
from synthea_explorer import (
    load_synthea,
    summarize,
    patient_timeline,
    patient_with_most_encounters,
    resource_counts,
    reference_edges,
    unresolved_references,
)

# A fixed "today" so ages are reproducible (the generator and the summary both use
# this same date - never date.today(), or the numbers would drift day to day).
AS_OF = date(2026, 1, 1)


# --- Page setup -----------------------------------------------------------------
st.set_page_config(page_title="Synthetic Population Explorer", page_icon=":hospital:",
                   layout="wide")

st.title("Synthetic Population Explorer")

# The banner that should never come off a health-tech demo.
st.warning(
    "Synthetic data only - this app invents fake patients with the Faker library. "
    "It never uses, stores, or accepts real patient data (PHI). Real PHI would need "
    "a BAA-covered environment, not free public hosting."
)

st.caption(
    "Generated by `synthea_mini` (a Java-free, schema-faithful stand-in for Synthea) "
    "and profiled by `synthea_explorer`. Same code your notebooks and tests run."
)


# --- The expensive bit: generate + load, cached so reruns are instant -----------
# Streamlit reruns the whole script on every interaction (clicking a button, moving
# a slider). @st.cache_data remembers the result for a given (n, seed) so we only do
# the real work when those inputs change, not every time you pick a patient.
@st.cache_data(show_spinner=True)
def build_dataset(n: int, seed: int):
    """Generate a population, write it to CSVs, load it back as DataFrames.

    Returns both the in-memory tables (dicts of rows, what the FHIR builder wants)
    and the loaded tables (DataFrames, what the explorer wants). We round-trip
    through real CSV files on purpose: it proves the explorer reads exactly what a
    real Synthea run would write to disk.
    """
    raw_tables = generate_population(n=n, seed=seed, as_of=AS_OF)

    # Write to a temporary folder, then load it back the way the explorer always does.
    tmp_dir = tempfile.mkdtemp(prefix="synthea_demo_")
    csv_dir = pathlib.Path(tmp_dir) / "csv"
    write_tables(raw_tables, csv_dir)
    loaded = load_synthea(csv_dir)

    return raw_tables, loaded


# --- Sidebar controls -----------------------------------------------------------
st.sidebar.header("Generate a population")
st.sidebar.write(
    "Pick how many patients to invent and a random seed. The same seed always "
    "produces the same population - that is what 'reproducible' means."
)

n_patients = st.sidebar.slider("Number of patients", min_value=5, max_value=200,
                               value=25, step=5)
seed = st.sidebar.number_input("Random seed", min_value=0, max_value=9999, value=12,
                               step=1)

# A button is optional here because we have sensible defaults: the app shows a
# population on first load without anyone clicking anything. The button just makes
# "regenerate" feel deliberate.
st.sidebar.button("Generate", type="primary")

# Defaults (25 patients, seed 12) mean the page is never blank on first visit.
raw_tables, tables = build_dataset(int(n_patients), int(seed))
summary = summarize(tables, as_of=AS_OF)


# --- Section 1: population summary ----------------------------------------------
st.header("1. Population at a glance")

col1, col2, col3 = st.columns(3)
col1.metric("Patients", summary["n_patients"])
col2.metric("Encounters", summary["n_encounters"])
mean_age = summary["age_stats"].get("mean", "-") if summary["age_stats"] else "-"
col3.metric("Mean age (years)", mean_age)

col4, col5 = st.columns(2)
col4.metric("Encounters per patient", summary["encounters_per_patient"])
age = summary["age_stats"]
age_range = f"{age['min']} - {age['max']}" if age else "-"
col5.metric("Age range", age_range)


# --- Section 2: charts ----------------------------------------------------------
st.header("2. What is in the data")
st.write(
    "Two quick views every analyst pulls first: how patients arrive at the system "
    "(encounter class) and what they are diagnosed with (top conditions)."
)

chart_left, chart_right = st.columns(2)

with chart_left:
    st.subheader("Encounters by class")
    # value_counts dicts -> a one-column DataFrame that st.bar_chart understands.
    # No matplotlib needed; st.bar_chart is built in.
    eclass = summary["encounter_class"]
    if eclass:
        eclass_df = pd.DataFrame({"count": eclass})
        st.bar_chart(eclass_df)
    else:
        st.info("No encounters in this population.")

with chart_right:
    st.subheader("Top conditions")
    conds = summary["top_conditions"]
    if conds:
        cond_df = pd.DataFrame({"count": conds})
        st.bar_chart(cond_df)
    else:
        st.info("No conditions recorded in this population.")


# --- Section 3: one patient's timeline ------------------------------------------
st.header("3. Take one patient apart")
st.write(
    "A patient is one person, but their record is scattered across files "
    "(encounters, conditions, observations, medications...) all linked by a "
    "PATIENT id. Stitch those rows together by date and you get a medical history."
)

# Build a readable label for the picker, but keep the real id for the lookups.
patients_df = tables["patients"]
busiest = patient_with_most_encounters(tables)

def patient_label(pid: str) -> str:
    row = patients_df[patients_df["ID"] == pid].iloc[0]
    return f"{row['FIRST']} {row['LAST']} ({pid[:8]})"

patient_ids = list(patients_df["ID"])
# Default the picker to the patient with the richest history - best for a demo.
default_index = patient_ids.index(busiest) if busiest in patient_ids else 0
chosen_id = st.selectbox("Pick a patient", patient_ids, index=default_index,
                         format_func=patient_label)

timeline = patient_timeline(tables, chosen_id)
st.subheader("Timeline")
if timeline.empty:
    st.info("This patient has no dated events.")
else:
    st.dataframe(timeline, use_container_width=True, hide_index=True)


# --- Section 4: the FHIR bundle for that patient --------------------------------
st.header("4. That patient as a FHIR bundle")
st.write(
    "FHIR is the standard for moving health data between systems. A Bundle packs "
    "one patient's resources together - a Patient, their Encounters, Conditions, "
    "Observations and so on - each pointing at the others with reference strings. "
    "Here is the bundle built from the same patient you picked above."
)

# build_patient_bundle works on the in-memory tables (raw_tables), not the loaded
# DataFrames - it reads the original row dicts.
bundle = build_patient_bundle(raw_tables, chosen_id)

bcol1, bcol2 = st.columns([2, 1])

with bcol1:
    st.subheader("Resources in the bundle")
    counts = resource_counts(bundle)  # a Counter: {resourceType: n}
    counts_df = pd.DataFrame(
        sorted(counts.items(), key=lambda kv: kv[1], reverse=True),
        columns=["Resource type", "Count"],
    )
    st.dataframe(counts_df, use_container_width=True, hide_index=True)

with bcol2:
    st.subheader("References resolve?")
    # A well-formed bundle is internally consistent: every reference points at a
    # resource that is actually in the bundle. unresolved_references returns the
    # broken ones - an empty list is the good outcome.
    unresolved = unresolved_references(bundle)
    n_edges = len(reference_edges(bundle))
    if not unresolved:
        st.success(f"PASS - all {n_edges} references resolve inside the bundle.")
    else:
        st.error(f"{len(unresolved)} of {n_edges} references are broken.")
        st.write(unresolved)

with st.expander("Show the raw FHIR JSON for this patient"):
    st.json(bundle)


st.divider()
st.caption(
    "Code: synthea_mini + synthea_explorer in build_from_scratch/. "
    "Real Synthea: https://synthetichealth.github.io/synthea/  -  "
    "Synthetic data only; never host real PHI."
)
